version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3000
      - PORT=3001
      - WATCHPACK_POLLING=true
    volumes:
      - /app/node_modules
      - ./frontend:/app
  backend:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      - DATABASE_URL=mongodb://mongo:27017/WebProg
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./server:/app
      - ./images:/images
  mongo:
    image: mongo
    ports:
      - "27018:27017"
  redis:
    image: redis
    ports:
      - "6380:6379"
