version: '3.8'
services:
  frontend:
    image: node:20-alpine3.16
    ports:
      - "3001:3001"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3000
    volumes:
      - ./frontend:/app

  backend:
    image: node:20-alpine3.16
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      - DATABASE_URL=mongodb://mongo:27017/WebProg
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./server:/app
      - ./images:/images

  mongo:
    image: mongo
    ports:
      - "27018:27017"
  redis:
    image: redis
    ports:
      - "6380:6379"
