version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3000
      - PORT=3001
    volumes:
      - ./frontend:/app
  backend:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - DATABASE_URL=mongodb://mongo:27017/WebProg
    volumes:
      - ./server:/app
      - ./images:/images
  mongo:
    image: mongo
    ports:
      - "27018:27017"
